### ISSUE TITLE
DFIRE is 0 for outer grid points

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#12]
<img width="379" alt="Screen Shot 2020-06-23 at 5 11 39 PM" src="https://user-images.githubusercontent.com/35278372/85463452-a6f30680-b574-11ea-84c2-8a3d69b0d824.png">
Except for the inner grid points, the DFIRE potentials return 0 as opposed to just low values. Also, the values overall are very low, with most between 0 and 0.1. I'm not sure if this is expected behaviour. Let me know if you have any ideas.

**Comment by andrewleber** [comment]
<img width="439" alt="Screen Shot 2020-06-23 at 5 13 55 PM" src="https://user-images.githubusercontent.com/35278372/85463779-ef122900-b574-11ea-9d3f-2e3ff8605b61.png">
This is how it looks with the protein on top, to show that the actual value is likely not 0.

**Comment by pulimeng** [comment]
What atom type is the grid points?

**Comment by andrewleber** [comment]
Not sure quite what you mean, I used the C.ar Potential if that's what you mean

**Comment by pulimeng** [comment]
Yes, that's what I meant. Is it similar for all other atom types? Or just this one?

**Comment by andrewleber** [comment]
Similar for all — I've attached a zip of the csv
[28997_3dgrid.csv.zip](https://github.com/pulimeng/DeepDrug3D/files/4822134/28997_3dgrid.csv.zip)

**Comment by andrewleber** [comment]
[28997_pot.pdb.zip](https://github.com/pulimeng/DeepDrug3D/files/4822171/28997_pot.pdb.zip)
[28997_trans.pdb.zip](https://github.com/pulimeng/DeepDrug3D/files/4822175/28997_trans.pdb.zip)
Here also are the transformed pdb and the grid with C.ar as the B factor if they help

**Comment by pulimeng** [comment]
Can you send me the pdb file?

**Comment by andrewleber** [comment]
The transformer pdb is above, here is the original (they are all zipped because github doesn't allow .pdb uplaod in comments)
[28997.pdb.zip](https://github.com/pulimeng/DeepDrug3D/files/4827531/28997.pdb.zip)

**Comment by pulimeng** [comment]
I think there is something wrong with your python code. I ran the DFIRE using the first point in the 28997_3dgrid.csv (C.2) against the transformed pbd. It gives me -13.465020.

**Comment by pulimeng** [comment]
Did you solve it?

**Comment by andrewleber** [comment]
Still working on it but I think you're right that it is due to my modifications, I'll comment what it was if I get it

**Comment by pulimeng** [comment]
Cool. Good luck.

**Comment by andrewleber** [comment]
I was using the .pdb instead of the .mol2, which is interesting that it even worked at all. Thanks again
