### ISSUE TITLE
dligand-linux is 32-bit binary

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#2]
The dligand-linux file can't be run on a 64-bit system without installing some libraries that are incompatible with my research server. Do you have a 64-bit binary?

**Comment by pulimeng** [comment]
Sorry. This is a pretty old script. They only have the 32-bit one. There are plenty of statistic potentials can be used to replace DFIRE, which is calculated by dligand-linux. You can maybe adopt one of those for your convenience.

**Comment by andrewleber** [comment]
Ah, that's alright. I appreciate the help.

**Comment by pulimeng** [comment]
You are welcome. I'm closing this issue.

**Comment by Luckick** [comment]
Hi, 

I am wondering which linux version is the dligand-linux compatible with? Is any website that I can refer to other versions of dligand?
I am using Ubuntu 16.04.7 LTS. 
When I run dligand-linux, no matter in python or command line, always shows bash: ./dligand-linux: Permission denied, even I log as root. I also follow https://askubuntu.com/questions/454253/how-to-run-32-bit-app-in-ubuntu-64-bit to run 32-bit app.

Any idea about this problem? 
Thank you!

**Comment by pulimeng** [comment]
Hi, 

I'm running RedHat Enterprise Linux 6 Operating System. There is no other source of dligand. However, if you wish you can have your own potential calculation software. It can be easily incorporated into the code. Have you tried chmod 777 dligand-linux then run it?

**Comment by Luckick** [comment]
Oh thanks!
"chmod 777 dligand-linux" works for me.

Now I am getting "Ppotential : No such file or directory" as andrewleber did. Where does the Ppotential come from? Should I make a folder named Ppotential somewhere?

**Comment by pulimeng** [comment]
fort.21_drug

**Comment by Luckick** [comment]
Awesome! It seems everything works. 

By the way, in the Github code, the voxelization.py:
`Grid3DBuilder.build(protein_coords, output_trans_mol2_path, r, N)`
I guess here we should use transformed_coords instead of protein_coords? Otherwise, the filters are based on original coordinates while the energy are based on rotated coordinates.

**Comment by pulimeng** [comment]
yes

**Comment by Luckick** [comment]
Thank you for your help!
