### ISSUE TITLE
dligand-linux not finding my mol2 files

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#3]
Every time I try to run dligand-linux, it gives the following error:

`Ppotential : No such file or directory`

Note that I have the required mol2 files in the same directory that I am running dligand-linux in and both files have full rwx privileges.

If it helps, I am on CentOS 7.

**Comment by pulimeng** [comment]
Did you run dligand-linux from python or just by itself? And can you copy your the code/command you used to run it?

**Comment by andrewleber** [comment]
I tried both. After running this in Python:
```
child = subprocess.Popen(['./dligand-linux', temp_filename, protein_file],
                                 stdout=subprocess.PIPE)
child.wait()
out = child.communicate()
print(out)
```
I got:
`Ppotential : No such file or directory`

I also just tried running `./dligand` by itself and I get `Usage: ./dligand-linux chain1_file chain2_file` and if I run `./dligand-linux test.mol2 test_aux_trans.mol2` I get `Ppotential : No such file or directory`

Any help is greatly appreciated

**Comment by pulimeng** [comment]
I just tried `./dligand-linux test.mol2 test_aux_trans.mol2`. It works with me. I think the problem might be the version of gcc. I have not encountered this problem at all before. Since the authors never releases the original code, I have no idea how to pin point the problem. Can you maybe try run it on a different machine?

**Comment by andrewleber** [comment]
Unfortunately I've tried running it on numerous Ubuntu versions and CentOS 6 and 7 and I was only able to get it to work at all on 7, but I guess it didn't fully work. Which distro/version are you running it on?

**Comment by pulimeng** [comment]
I know this is frustrated. The paper is relatively early and the code is compiled using some legacy version of compiler. Thus, it would not run on most of the current machines. I cannot get it to run on my desktop, which is CentOS 7. I have run it on the school server, which uses RedHat Enterprise Linux 6 Operating System.

**Comment by andrewleber** [comment]
What error are you getting on your CentOS system? I just set up a GCP VM with RedHat Enterprise Linux 6 OS and I've been getting the same `Ppotential : No such file or directory` error.

**Comment by pulimeng** [comment]
I get the `./dligand-linux: error while loading shared libraries: libstdc++-libc6.2-2.so.3: cannot open shared object file: No such file or directory` error on my CentOS desktop. Just to make sure, did you put the file `fort.21_drug` under the same directory with dligand-linux?

**Comment by andrewleber** [comment]
It was not in the same directory! I was only using the repo for the binding pocket voxelization in 5D and not the CNN so I just took what files I thought I needed. I placed the two files together and now it seems to work. Thanks a bunch.

By the way, I had the same error until I did `sudo yum install libstdc++-libc6.2-2.so.3`, if you ever wanted to run it on your desktop.

Cheers!
