### ISSUE TITLE
site_refine removes all of my points

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#4]
When using the site_refine function, all of my points end up being removed.

The length of `inside_side` is 318, then the length of `hull_site` is 18, then the length of `cluster_labels` is 0, which then results in the error: ```IndexError: index 0 is out of bounds for axis 0 with size 0``` because the array is empty.

 I don't know if it is standard for `hull_site` to be so much smaller than `inside_site`, but there is no way that `cluster_labels` can be 0. Any help would be appreciated.

**Comment by pulimeng** [comment]
It is usual but can happen. Like when the protein is relatively "flat" or very small. I think you should manually exam the pdb file and highlight the points of `inside_site`. This will give you an idea of how the convex hull goes. If the convex hull is in odd shape. You can just remove the convex hull step. This is step is to make sure every point is roughly in the shape of the protein. Since your `hull_site` is so small, I don't think you want to remove isolated grid points. They could be isolated anyway. It would be better if you can provide pdbid or .pdb file.

**Comment by andrewleber** [comment]
I attached the PDB here (Github doesn't accept .pdb so I had to zip it):
[test2.pdb.zip](https://github.com/pulimeng/DeepDrug3D/files/3730641/test2.pdb.zip)

So you think I should just skip the convex hull and isolated points step?

**Comment by pulimeng** [comment]
Can you tell me the pocket residue number ?

**Comment by andrewleber** [comment]
`BindingResidueIDs:179 180 181 247 248 249 250 270 271 272 273 274 275 279 298 363 375 378`

**Comment by andrewleber** [comment]
I seemed to have partially fixed it by changed by values of r and N, I changed it to the defaults of 15 and 31 and now the lengths are `5320`, `5320`, and `15` respectively. Is 15 still too small and I should skip it?

**Comment by pulimeng** [comment]
I've looked at the protein and the binding site. I think the reason that `hull_site` is so small is that your pocket is close to the surface of the protein. Thus, many grid points will naturally fall outside the convex hull of the protein. I would suggest remove the convex hull only or use the smaller `r`. I'm not sure the exact value but you can play with it to get a feeling

**Comment by andrewleber** [comment]
The hull problem actually seemed to have been fixed with r and N. I was using a greater r value than N which seemed to have caused the error. I don't know if the value of 15 is still too small, though. Should I skip this step?

**Comment by pulimeng** [comment]
Ideally, you don't want to skip it. If you can get it to work by adjusting `r` and `N`. I would still do this step since it prevents your binding site to grow too far outside of the protein.

**Comment by andrewleber** [comment]
Okay, thank you for your help on this issue.
