### ISSUE TITLE
minmax_scale divides by 0

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#5]
When minmax_scale is used, it reports that I am dividing by 0 because `X.max(axis=axis) - X.min(axis=axis)` is equal to 0.

I looked into why and the input seems to be a repeating array over and over again, which itself seems to be a larger issue. The array is ```[[-56169.531419 -56188.813073 -56178.434172 -56130.495976 -56165.063472
  -56168.170667 -56107.861037 -55892.40289  -56102.923331 -56152.533155
  -56158.525596 -56064.797977 -55945.989211 -56097.680511]]``` for each `loc1` in `binding_site` (the above is the output for `loc1 in binding_site[:1]`)

Obviously, the array is not supposed to repeat again and again, so I guess the issue arises from that. Any help is greatly appreciated.

**Comment by pulimeng** [comment]
I don't understand the problem. In the array you provided, the `min` is certainly not equal to the `max`.

**Comment by andrewleber** [comment]
To clarify, the displayed subarray occurs repeatedly every line. 

If the above array is equal to x, then the array is [x x x x x x x] with the number of x's equal to `len(binding_site)`. 

This is the array for `binding_site[:3]`:
[[-56169.531419 -56188.813073 -56178.434172 -56130.495976 -56165.063472
  -56168.170667 -56107.861037 -55892.40289  -56102.923331 -56152.533155
  -56158.525596 -56064.797977 -55945.989211 -56097.680511]
 [-56169.531419 -56188.813073 -56178.434172 -56130.495976 -56165.063472
  -56168.170667 -56107.861037 -55892.40289  -56102.923331 -56152.533155
  -56158.525596 -56064.797977 -55945.989211 -56097.680511]
 [-56169.531419 -56188.813073 -56178.434172 -56130.495976 -56165.063472
  -56168.170667 -56107.861037 -55892.40289  -56102.923331 -56152.533155
  -56158.525596 -56064.797977 -55945.989211 -56097.680511]]

**Comment by andrewleber** [comment]
If you require any other information I would be happy to provide it. I think this is the last error since it still runs, though bugged. Thank you for your continued help and I will be sure to cite DeepDrug3D in any publications that arise form my work.

**Comment by pulimeng** [comment]
Sorry man. I'm a little occupied right now. I will take a look at it this weekend.

**Comment by andrewleber** [comment]
Sorry to bug you, I tried restarting the whole implementation and this time I think I got it working work. I must have changed something when I first started using it (and tried converting it to python 3) but now it seems to work in Python 2. I'll test it and if it works I'll close the issue. I'll let you know if anything else comes up. All the best, Andrew

**Comment by pulimeng** [comment]
I'm glad to help its just I'm kinda busy recently with other projects. Nice you figured it out. There could be some grammar changes between python 2 and 3 involved in the code. Just let me know if it works. If not, I can take a look at it this weekend.

**Comment by andrewleber** [comment]
After running it in Python 2 the first points had different values for dligand but the last points all had the same values (see screenshot). This seems to be similar to the original issue but now only for some points.
<img width="576" alt="Code screenshot" src="https://user-images.githubusercontent.com/35278372/67120559-8984c600-f1b7-11e9-87e4-a6213fd4b100.png">

**Comment by andrewleber** [comment]
I just looked through all the data and it seems like there are pockets of between 1-30 points that all have the same value of `[ 36.86776105  45.96107972  47.90900504 -11.54191708  27.85451515
   6.92742989  27.81152082  -2.99893597  15.87963853  24.13789291
  33.42091148   1.7651835   -1.69387705  31.90938713]` and then the last couple of hundred points all have this value as well, as you can partially see from the screenshot above. Is this some sort of NaN value? If so, how can I get the true values?

**Comment by pulimeng** [comment]
Can you visually check the points with same values? It might because that they are too far from the protein. Thus, they fall into the same bin when you calculate the potential energy.

**Comment by andrewleber** [comment]
It seems that generally the points with this value have at least one coordinate above 12 (max of 15) so that could be it. I guess for now I can close the issue and I'll assume that is what is going on. Thanks

**Comment by pulimeng** [comment]
Hope it solve your problem. That's why we remove the points too far away from the protein using convex hull in the first place.
