### ISSUE TITLE
Voxel is just 1.'s

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#6]
My voxel just ends up being:
```
[[[[[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]

   [[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]

   [[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]

   ...

   [[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]

   [[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]

   [[1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    ...
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]
    [1. 1. 1. ... 1. 1. 1.]]]
```

I went into debug mode and noticed that cnt was not 0 and in fact in the thousands, so it doesn't seem like the site_voxelization function is just recognizing them as too far. As always, any help is greatly appreciated.

**Comment by pulimeng** [comment]
Can you check the array by using np.min np.mean or something like this. Cause the empty space is padded with 1's. So the visible 1's might just be the padding number.

**Comment by pulimeng** [comment]
You can subtract the array by 1 and count the nonzeros. If everything is 1, the count should be 0.

**Comment by andrewleber** [comment]
You are right, there was just a lot of padding. Thank you so much! One more thing -- how did you visualize the voxels as in the photo in your readme?

**Comment by pulimeng** [comment]
You are welcome. By creating dummy pdb files from the grid point representation (not voxel). For each grid points you create a row in a pdb file based on the specific of the pdb format. You just need coordinates and b-factor (for coloring). Something like the following.

# make line from grid point rep to .pdb file for visualization
num_range = np.linspace(0,25,26, dtype = int)
chr_range = list(string.ascii_uppercase[:27])
num_chr_dict = dict(zip(num_range,chr_range))
```
def makeLine(coord, potE, k, num_chr_dict):
    atom = 'ATOM'
    atom_sn = str(k+1)
    atom_name = 'D1'
    hundred, one = np.divmod(k,676)
    ten, one = np.divmod(k-hundred*676,26)
    res_name = num_chr_dict[hundred] + num_chr_dict[ten] + num_chr_dict[one]
    E = potE
    x = '{:.3f}'.format(round(coord[0], 3))
    y = '{:.3f}'.format(round(coord[1], 3))
    z = '{:.3f}'.format(round(coord[2], 3))
    EE = '{:.2f}'.format(round(E,2))
    string = atom + ' '*2 + '{:>5}'.format(atom_sn) + ' ' + '{:4}'.format(atom_name) + ' ' \
            + '{:>3}'.format(res_name) + ' '*2 + '   1' + ' '*4 + '{:>8}'.format(x) + '{:>8}'.format(y) + '{:>8}'.format(z) \
            + '{:>6}'.format('1.00') + '{:>6}'.format(EE) + ' '*8 + '\n'
    return string
```
It names each atom from AAA to ZZZ based on how many atoms you have.

**Comment by andrewleber** [comment]
Thank you for this -- what is the k value in the function?

**Comment by pulimeng** [comment]
Just number of points.

Here is an example of how to use it.
```
with open (protein_name + '_site_original.pdb','w') as in_strm:
    for k in xrange(len(BS_original)):
        temp_coords = BS_original[k,:]
        cl = temp_coords[-1]
        temp_string = makeLine(temp_coords, cl, k, num_chr_dict)
        in_strm.write(temp_string)
print('Number of points is ' + str(len(BS_original)))
```
The following is an example of generated pdb file.
```
ATOM      1 D1   AAA     1      -5.000 -11.000  -5.000  1.00  0.80        
ATOM      2 D1   AAB     1      -6.000  -9.000  -5.000  1.00  0.59        
ATOM      3 D1   AAC     1      -6.000 -10.000  -5.000  1.00  0.65        
ATOM      4 D1   AAD     1      -5.000  -9.000  -5.000  1.00  0.64        
ATOM      5 D1   AAE     1      -5.000 -10.000  -5.000  1.00  0.76        
ATOM      6 D1   AAF     1      -5.000  -9.000  -6.000  1.00  0.72        
ATOM      7 D1   AAG     1      -7.000 -10.000  -4.000  1.00  0.64        
ATOM      8 D1   AAH     1      -7.000  -9.000  -4.000  1.00  0.60        
ATOM      9 D1   AAI     1      -6.000 -10.000  -4.000  1.00  0.66        
ATOM     10 D1   AAJ     1      -5.000  -9.000  -4.000  1.00  0.77        
ATOM     11 D1   AAK     1      -6.000  -9.000  -4.000  1.00  0.64        
ATOM     12 D1   AAL     1      -1.000 -11.000  -8.000  1.00  0.71        
ATOM     13 D1   AAM     1      -1.000 -10.000  -7.000  1.00  0.67        
ATOM     14 D1   AAN     1      -1.000 -10.000  -8.000  1.00  0.66        
ATOM     15 D1   AAO     1      -1.000  -9.000  -8.000  1.00  0.54        
```

**Comment by andrewleber** [comment]
Sorry if I'm being a bit dense, but at what point would I run this? I ran this assuming that BS_original is the output from Grid3DBuilder but I got `TypeError: '(0, slice(None, None, None))' is an invalid key` for `temp_coords = pocket_grid[k, :]`

**Comment by pulimeng** [comment]
Just when you wanna visualize your pocket in terms of the grid points. I actually visualized every step of the binding site refine process. That's how I got the flow chart in the paper. I think the function expects an array while Grid3DBuilder outputs a DataFrame. Anyway it is just an simple example. You might need to revise the code accordingly.

**Comment by andrewleber** [comment]
Ah, I see. I got it to work for the grid in site_refine. How did you align the grid and the protein? Also, how did you colour the points according to DFIRE potentials?

**Comment by pulimeng** [comment]
You use transformed pdb from `voxelization.py`.  I put the potential at the position where the pdb holds the b-factor and pymol can color according to b-factor.

**Comment by andrewleber** [comment]
I see. Do you have the code that you used for that? Just for consistency's sake (and also not to waste time coding something twice over)

**Comment by pulimeng** [comment]
The `makeLine` function does the writing pdb job. I cannot remember the pymol command but just google it. It's easy to find

**Comment by andrewleber** [comment]
Oh I see, I thought you meant I needed another function on top of makeLine to add the potential colours. I looked into the PyMol colour by b-factor but wasn't able to get it working. I ran the commands at https://pymolwiki.org/index.php/Advanced_Coloring#Assign_color_by_B-factor but after running `spectrum b, blue_white_red, minimum=20, maximum=50` it just adopted a spectrum of colours, not according to their potE. I realize that is outside of the scope of DeepDrug3D but I'd appreciate any help.

**Comment by pulimeng** [comment]
I think you have to specify the selection to be those grid points

**Comment by andrewleber** [comment]
I've been fussing around with the functions but I think I found my error, I compared your sample PDB to mine and your last column (which I believe is the B-factor) look much different than mine. Yours are floats between 0.0 and 1.0 whereas mine look like this:
````
ATOM      1 D1   AAA   1      -1.000  -2.000  -1.000  1.00 -1.00        
ATOM      2 D1   AAB   1      -1.000  -1.000  -1.000  1.00 -1.00        
ATOM      3 D1   AAC   1      -2.000  -1.000  -1.000  1.00 -1.00        
ATOM      4 D1   AAD   1      -1.000  -2.000  -2.000  1.00 -2.00        
ATOM      5 D1   AAE   1      -1.000  -1.000  -3.000  1.00 -3.00        
ATOM      6 D1   AAF   1      -1.000  -1.000  -2.000  1.00 -2.00        
ATOM      7 D1   AAG   1      -1.000  -5.000   3.000  1.00  3.00        
ATOM      8 D1   AAH   1      -1.000  -6.000   6.000  1.00  6.00        
ATOM      9 D1   AAI   1      -1.000  -6.000   7.000  1.00  7.00        
ATOM     10 D1   AAJ   1      -1.000  -5.000   4.000  1.00  4.00  

````
It sort of makes sense though, because I'm not sure how we can assign potE values before we calculate that? (Since site_refine is before potE) As always, I really appreciate the help

**Comment by pulimeng** [comment]
I think I had a different file that has all the outputs. I just picked some files to visualize individually from the generation process.

**Comment by andrewleber** [comment]
Ah I see; but my question still stands, which is how do I use the calculated potE for the b-factor rather than what appears to be uniform integers? Attached is an image of how the voxel's colour seems to be according to b-factor.
<img width="505" alt="Screen Shot 2019-10-28 at 2 36 08 PM" src="https://user-images.githubusercontent.com/35278372/67707131-54832b00-f990-11e9-9326-76f05808bc9d.png">

**Comment by pulimeng** [comment]
What I did is I save all the grid points information (coordinates and potential energy for each atom type) to an .csv file since it takes a while to generate one grid representation for a pocket. I don't want to have to do it over and over again. And in the makeLine function, you should input your potential energy by reading rows from the .csv file. The attached is an example of the .csv file.
```
x y z C.2 C.3 C.ar F N.am N.2 O.co2 N.ar S.3 O.2 O.3 N.4 P.3 N.pl3
-11.0 -9.0 -5.0 0.493282688721 0.784479098275 0.863170614535 0.121997136269 0.351124434837 0.777070665064 0.543165030769 0.472690141087 0.313007908475 0.552851593577 0.485828444615 0.15140922481 0.517682336611 0.539063147856
-9.0 -11.0 -5.0 0.525988465871 0.676200618205 0.738230317134 0.0414844638782 0.433695547441 0.720275520734 0.398962225045 0.187852785311 0.263029846462 0.549156033628 0.43595001676 0.0868656664577 0.331967411119 0.46006799654
-9.0 -9.0 -7.0 0.486567009234 0.61879560057 0.740417107445 0.0388727884758 0.396164991661 0.713389224997 0.403441641134 0.194469634888 0.267779232945 0.568852436418 0.435396643849 0.0970751250036 0.334522498001 0.468184357578
-10.0 -9.0 -6.0 0.435133425429 0.57057325944 0.763790975197 0.134735684459 0.355437531605 0.705691953282 0.45506364077 0.359922205517 0.280285914613 0.556111273028 0.42003871594 0.116288438622 0.421934888354 0.471355163553
-10.0 -9.0 -5.0 0.456351074955 0.568978805906 0.748578557403 0.0321611231955 0.336506541208 0.707388055999 0.444753307373 0.354898708002 0.279699593983 0.518465112118 0.395590349759 0.0962587437538 0.42748088358 0.442377030889
```

**Comment by andrewleber** [comment]
I see, that makes sense. Is the potE the average of the row of potential energies? How did you get a single number from all of them?

**Comment by pulimeng** [comment]
I just took one channel to show as example. You can tell from the README. I mentioned it is C.ar channel.

**Comment by andrewleber** [comment]
Wonderful! Thanks
<img width="441" alt="Screen Shot 2019-10-29 at 3 36 12 PM" src="https://user-images.githubusercontent.com/35278372/67802611-de4ef900-fa61-11e9-9373-f9e1d38d338d.png">
