### ISSUE TITLE
minmax_scale() function

### ISSUE THREAD

**Issue by wildberry93** [pulimeng/DeepDrug3D#7]
Hi!

Thank you for this cool tool!
I'm having an error in minmax_scale() function though. In line:
`X_scaled = X_std * (X.max - X.min) + X.min`
`TypeError: unsupported operand type(s) for -: 'builtin_function_or_method' and 'builtin_function_or_method'`

X.min and X.max should be max(X) and min(X)?

Thank you!

**Comment by pulimeng** [comment]
can you try X.max() same for the min

**Comment by wildberry93** [comment]
Worked, thank you!
