### ISSUE TITLE
Grid isn't near chosen residues

### ISSUE THREAD

**Issue by andrewleber** [pulimeng/DeepDrug3D#8]
Thanks for your help with visualizing the grid and that is successful now, and I was able to visualize it on top of the protein as well. However, I can now see that the grid is not near the specified BindingResidueIDs that I had specified in test_aux.txt. I have highlighted these residues in red and visualized the grid and you can see that they are a quite far apart. Any help is greatly appreciated.
<img width="479" alt="Screen Shot 2019-10-29 at 9 39 28 PM" src="https://user-images.githubusercontent.com/35278372/67821864-e70cf280-fa94-11e9-8f28-a3395c0669bc.png">

**Comment by pulimeng** [comment]
could be the problem with alignment. does the shown points intersect with any of the protein atoms?

**Comment by andrewleber** [comment]
On the image above (which is the grid visualized alongside the original pdb input), there are some point where the grid overlaps. Having said that, there are also other times where the grid does seem to make room for the protein

 I'm not sure if it is the right image at all, but when I image the grid alongside the aux_trans pdf it is much worse and clearly not aligned. Perhaps there is an alignment step I am missing.

<img width="353" alt="Screen Shot 2019-10-31 at 11 15 08 PM" src="https://user-images.githubusercontent.com/35278372/67999862-4a815680-fc34-11e9-8a49-1e3ac4cdcdb4.png">

**Comment by pulimeng** [comment]
If there is overlap it is definitely an alignment problem. Did you change anything regarding the alignment in the scripts? It looks like the proteins in the two figures are the same orientation.

**Comment by andrewleber** [comment]
If by the alignment you mean the stuff in Vox3DBuilder then no, I have not changed it. The two proteins, test.pdb and test_aux_trans.pdb, are not in the same position.

The following two are about the original file, test.pdb.
Sometimes the grid does seem to contour around the protein as in this photo:
<img width="302" alt="Screen Shot 2019-11-03 at 12 37 54 AM" src="https://user-images.githubusercontent.com/35278372/68080458-307d7a80-fdd2-11e9-8b33-374ef9c13d0f.png">

But sometimes overlaps as in this photo:
<img width="238" alt="Screen Shot 2019-11-03 at 12 38 14 AM" src="https://user-images.githubusercontent.com/35278372/68080459-3a06e280-fdd2-11e9-9370-25d2a454f429.png">

Maybe most significantly is the grid is not in the convex hull of the protein for either file.

**Comment by pulimeng** [comment]
Hmm. I'm not sure what is happening here. Did you change anything in binding_grid.py? I think you'll have to output the intermediate results of the site_refinement and visualize them to figure out what is wrong.

I had a code `BS_refine_process.py` that analyze the process step by step. I just uploaded it to the repo. You can revise it to suit your data.

**Comment by andrewleber** [comment]
I change some things but nothing about the site location; thank you for BS_refine and I'll try rebuilding the whole thing again to get it to work

**Comment by andrewleber** [comment]
@pulimeng, is the ligand in BS_refine equivalent to the final output for the binding grid? If so, could the issue be that I just input "1 1 1" as the binding site centre? Perhaps that was the cause of the error from the beginning. Where can I find a more accurate binding site centre?

**Comment by pulimeng** [comment]
If you don't know the center the program will calculate the center based on the binding residues. Don't manually input the wrong center. There are several lines for the center calculation in `voxelization.py` .

**Comment by andrewleber** [comment]
<img width="540" alt="Screen Shot 2019-12-02 at 12 15 42 PM" src="https://user-images.githubusercontent.com/35278372/69980082-84789d80-14fd-11ea-9307-7d4fc648dfe9.png">
I didn't input the centre and the position changed (definitely closer to the actual pocket) but it still seems there is some protein overlap.

**Comment by pulimeng** [comment]
Looks like a alignment problem. Either the protein is not aligned to the PAs or the pocket is not aligned to the PAs. There are two functions in `voxelization.py`, https://github.com/pulimeng/DeepDrug3D/blob/70ebbef5e4f56d63eb3d68fa77aec57c630c89ad/voxelization.py#L53-L87
can you check if you used those correctly. I suggest you look into `voxelization.py` and follow the steps since you only tried to extract the pocket representation. There might be something you missed.

**Comment by andrewleber** [comment]
I did not change those two functions in `voxelization.py`, so I don't think that will be the issue.

Is there a way to extract the pocket representation from the output of `voxelize` as opposed to the binding grid file? Maybe that is the issue as the alignment happens in `voxelize` and not in binding grid.z

Happy new year, by the way! Thanks a lot for your continued help.

**Comment by pulimeng** [comment]
Can you verify that the protein you show in your previous comment on Dec. 2 is the transformed protein?

**Comment by andrewleber** [comment]
Yes I have confirmed that is is the aux_trans protein. Should I just try rebuilding everything once more? Or do you have another idea of what it could be.

**Comment by pulimeng** [comment]
I have no idea what it could be right now. Can you share the pdb file you are using and the binding residue number . I'll take a look at it. In the mean time you can rebuild everything just to make sure nothing is messed up.

**Comment by andrewleber** [comment]
Here is the pdb (zipped because GitHub doesn't take pdb files) and the aux file with the binding residues. 
[test_domain_aux.txt](https://github.com/pulimeng/DeepDrug3D/files/4047569/test_domain_aux.txt)
[test2.pdb.zip](https://github.com/pulimeng/DeepDrug3D/files/4047558/test2.pdb.zip)

Thanks a ton for your help.

**Comment by andrewleber** [comment]
Any update on this?

**Comment by pulimeng** [comment]
Sorry. I've been busy. I'll try to look at it this weekend.

**Comment by pulimeng** [comment]
Sorry for the delay. I looked at it. Everything seems correct on my side . The pocket looks like the following.
![test2](https://user-images.githubusercontent.com/22781918/74179938-14287f80-4c04-11ea-971c-83d0186435cb.png)
I think you might used the original protein coordinates to calculate the pairwise distances. You need to use the transformed protein coordinates to calculate the distances. I've attached the script I used to test it. Let me know if it works.
```
import numpy as np
import pandas as pd
from biopandas.pdb import PandasPdb

from scipy.spatial.distance import cdist
import scipy
from scipy.spatial import Delaunay
from sklearn.cluster import DBSCAN

import string

# Parse the mol2 file
def parseMol2(pmol):
    atType = pmol.df['atom_type']
    coord = pmol.df[['x', 'y', 'z']]
    subset_name = pmol.df['subst_name']
    frames = pd.concat([atType,coord,subset_name], axis = 1)
    return frames
# Generate sphere grid points
def sGrid(center, r, N):
    center = np.array(center)
    x = np.linspace(center[0]-r,center[0]+r,N)
    y = np.linspace(center[1]-r,center[1]+r,N)
    z = np.linspace(center[2]-r,center[2]+r,N)
    #Generate grid of points
    X,Y,Z = np.meshgrid(x,y,z)
    data = np.vstack((X.ravel(),Y.ravel(),Z.ravel())).T
    # indexing the interior points
    tree = scipy.spatial.cKDTree(data)
    mask = tree.query_ball_point(center,1.01*r)
    points_in_sphere = data[mask]
    return points_in_sphere
# make line for pdb file
def makeLine(coord, potE, k, num_chr_dict):
    atom = 'ATOM'
    atom_sn = str(k+1)
    atom_name = 'D1'
    hundred, one = np.divmod(k,676)
    ten, one = np.divmod(k-hundred*676,26)
    res_name = num_chr_dict[hundred] + num_chr_dict[ten] + num_chr_dict[one]
    E = potE
    x = '{:.3f}'.format(round(coord[0], 3))
    y = '{:.3f}'.format(round(coord[1], 3))
    z = '{:.3f}'.format(round(coord[2], 3))
    EE = '{:.2f}'.format(round(E,2))
    string = atom + ' '*2 + '{:>5}'.format(atom_sn) + ' ' + '{:4}'.format(atom_name) + ' ' \
            + '{:>3}'.format(res_name) + ' '*2 + '   1' + ' '*4 + '{:>8}'.format(x) + '{:>8}'.format(y) + '{:>8}'.format(z) \
            + '{:>6}'.format('1.00') + '{:>6}'.format(EE) + ' '*8 + '\n'
    return string
# test if a point is inside a convex hull
def in_hull(p, hull):
    if not isinstance(hull,Delaunay):
        hull = Delaunay(hull)
    return hull.find_simplex(p)>=0
# parse the input auxilary file
def parse_aux(path):
    content = []
    with open(path, 'r') as in_strm:
        for line in in_strm.readlines():
            l = line.replace('\n','')
            idx = l.index(':')
            content.append(l[idx+1:None])
    resi =  [int(x) for x in content[0].split(' ')]
    if len(content[1]) > 0:
        return resi, int(content[1])
    else:
        return resi, None
# rotations and transformations for the alignment
def normalize(v):
    """ vector normalization """
    norm = np.linalg.norm(v)
    if norm == 0: 
       return v
    return v / norm

def vrrotvec(a,b):
    """ Function to rotate one vector to another, inspired by
    vrrotvec.m in MATLAB """
    a = normalize(a)
    b = normalize(b)
    ax = normalize(np.cross(a,b))
    angle = np.arccos(np.minimum(np.dot(a,b),[1]))
    if not np.any(ax):
        absa = np.abs(a)
        mind = np.argmin(absa)
        c = np.zeros((1,3))
        c[mind] = 0
        ax = normalize(np.cross(a,c))
    r = np.concatenate((ax,angle))
    return r

def vrrotvec2mat(r):
    """ Convert the axis-angle representation to the matrix representation of the 
    rotation """
    s = np.sin(r[3])
    c = np.cos(r[3])
    t = 1 - c
    
    n = normalize(r[0:3])
    
    x = n[0]
    y = n[1]
    z = n[2]
    
    m = np.array(
     [[t*x*x + c,    t*x*y - s*z,  t*x*z + s*y],
     [t*x*y + s*z,  t*y*y + c,    t*y*z - s*x],
     [t*x*z - s*y,  t*y*z + s*x,  t*z*z + c]]
    )
    return m

# load the data
protein_name = 'test'
protein_path = 'test2.pdb'
ppdb = PandasPdb().read_pdb(protein_path)
protein_df = ppdb.df['ATOM']
resi, ct = parse_aux('./test_domain_aux.txt')
if ct != None:
    pocket_df = protein_df[protein_df['residue_number'].isin(resi)]
    pocket_coords = np.array([pocket_df['x_coord'], pocket_df['y_coord'], pocket_df['z_coord']]).T
    pocket_center = np.array([int(x) for x in ct.split(' ')])
else:
    print('No center is provided')
    pocket_df = protein_df[protein_df['residue_number'].isin(resi)]
    pocket_coords = np.array([pocket_df['x_coord'], pocket_df['y_coord'], pocket_df['z_coord']]).T
    pocket_center = np.mean(pocket_coords, axis = 0)
protein_coords = np.array([protein_df['x_coord'], protein_df['y_coord'], protein_df['z_coord']]).T
pocket_coords = pocket_coords - pocket_center # center the pocket to 0,0,0
protein_coords = protein_coords - pocket_center # center the protein according to the pocket center
inertia = np.cov(pocket_coords.T)
e_values, e_vectors = np.linalg.eig(inertia)
sorted_index = np.argsort(e_values)[::-1]
sorted_vectors = e_vectors[:,sorted_index]
# Align the first principal axes to the X-axes
rx = vrrotvec(np.array([1,0,0]),sorted_vectors[:,0])
mx = vrrotvec2mat(rx)
pa1 = np.matmul(mx.T,sorted_vectors)
# Align the second principal axes to the Y-axes
ry = vrrotvec(np.array([0,1,0]),pa1[:,1])
my = vrrotvec2mat(ry)
transformation_matrix = np.matmul(my.T,mx.T)
# transform the protein coordinates to the center of the pocket and align with the principal
# axes with the pocket
transformed_coords = (np.matmul(transformation_matrix,protein_coords.T)).T
# Generate a new pdb file with transformed coordinates
ppdb.df['ATOM']['x_coord'] = transformed_coords[:,0]
ppdb.df['ATOM']['y_coord'] = transformed_coords[:,1]
ppdb.df['ATOM']['z_coord'] = transformed_coords[:,2]
output_trans_pdb_path = protein_name + '_trans.pdb'
print('Output the binding pocket aligned pdb file to: ' + output_trans_pdb_path)
ppdb.to_pdb(output_trans_pdb_path)
    
num_range = np.linspace(0,25,26, dtype = int)
chr_range = list(string.ascii_uppercase[:27])
num_chr_dict = dict(zip(num_range,chr_range))
# original sphere BS
BS_original = sGrid(pocket_center, 15, 31)
BS_original = np.concatenate((BS_original,np.zeros((len(BS_original),1))), axis = 1)
with open (protein_name + '_site_original.pdb','w') as in_strm:
    for k in range(len(BS_original)):
        temp_coords = BS_original[k,:]
        cl = temp_coords[-1]
        temp_string = makeLine(temp_coords, cl, k, num_chr_dict)
        in_strm.write(temp_string)
print('Number of points is ' + str(len(BS_original)))
# Remove points too close to the protein (less than 2 A)
dist = cdist(BS_original[:,0:3], transformed_coords, 'euclidean')
BS_2close1 = []
for i in range(len(dist)):
    temp = BS_original[i,:]
    if np.any(dist[i,:] < 2.1):
        temp[-1] = 1
        BS_2close1.append(temp)
    else:
        temp[-1] = 0
        BS_2close1.append(temp)
BS_2close1 = np.array(BS_2close1)
with open (protein_name + '_site_2close1.pdb','w') as in_strm:
    for k in range(len(BS_2close1)):
        temp_coords = BS_2close1[k,:]
        cl = temp_coords[-1]
        temp_string = makeLine(temp_coords, cl, k, num_chr_dict)
        in_strm.write(temp_string)
BS_2close2 = []
for i in range(len(dist)):
    temp = BS_original[i,:]
    if np.any(dist[i,:] < 2.1):
        continue
    else:
        BS_2close2.append(temp)
BS_2close2 = np.array(BS_2close2)
with open (protein_name + '_site_2close2.pdb','w') as in_strm:
    for k in range(len(BS_2close2)):
        temp_coords = BS_2close2[k,:]
        cl = temp_coords[-1]
        temp_string = makeLine(temp_coords, cl, k, num_chr_dict)
        in_strm.write(temp_string)
print('Number of points after removing points close to the protein is ' + str(len(BS_2close1)))
# Remove points outside the convex hull
hull_labels = in_hull(BS_2close2[:,0:3], protein_coords)
BS_inhull1 = BS_2close2[hull_labels]
with open (protein_name + '_site_inhull1.pdb','w') as in_strm:
    for k in range(len(BS_inhull1)):
        temp = BS_inhull1[k,:]
        cl = temp[3]
        temp_string = makeLine(temp, cl, k, num_chr_dict)
        in_strm.write(temp_string)
BS_inhull2 = []
for k in range(len(hull_labels)):
    temp = BS_2close2[k,:]
    if hull_labels[k]:
        temp[-1] = 1
        BS_inhull2.append(temp)
    else:
        temp[-1] = 0
        BS_inhull2.append(temp)
BS_inhull2 = np.array(BS_inhull2)
with open (protein_name + '_site_inhull2.pdb','w') as in_strm:
    for k in range(len(BS_inhull2)):
        temp = BS_inhull2[k,:]
        cl = temp[3]
        temp_string = makeLine(temp, cl, k, num_chr_dict)
        in_strm.write(temp_string)
print('Number of points after removing points outside the convex hull of the protein is ' + str(len(BS_inhull1)))
# remove isolated grid points
iso_dist = cdist(BS_inhull1[:,0:3],BS_inhull1[:,0:3])
labels = DBSCAN(eps = 1.414, min_samples = 3, metric = 'precomputed').fit_predict(iso_dist)
unique, count = np.unique(labels, return_counts = True)
sorted_label = [x for _,x in sorted(zip(count,unique))]
sorted_label = np.array(sorted_label)
null_index = np.argwhere(sorted_label == -1)
cluster_labels = np.delete(sorted_label, null_index)
save_labels = np.flip(cluster_labels, axis = 0)[0]
final_label = np.zeros(labels.shape)
for k in range(len(labels)):
    if labels[k] == save_labels:
        final_label[k] = 1
    else:
        continue
iso_site = []
cnt = 0
for j in range(len(final_label)):
    if final_label[j] == 1:
        temp = np.append(BS_inhull1[j,0:3],np.array(1))
        iso_site.append(temp)
        cnt += 1
    else:
        temp = np.append(BS_inhull1[j,0:3],np.array(0))
        iso_site.append(temp)
iso_site = np.array(iso_site)
with open (protein_name + '_site_cc2.pdb','w') as in_strm:
    for k in range(len(iso_site)):
        temp_c = iso_site[k,:]
        potE_c = temp_c[3]
        temp_string = makeLine(temp_c, potE_c, k, num_chr_dict)
        in_strm.write(temp_string)
print('Number of points after removing points not connected to the main site is ' + str(cnt))
```

**Comment by andrewleber** [comment]
That is good to know re:using the transformed coordinates for the potE calculations, but if you highlight the residues in the aux file they still don't seem to be near the pocket that you attached. (see my first photo in this thread for a visual representation of what I mean). Let me know if you need any more clarification. Also sorry for the long delays, I needed to wrap up another project.

**Comment by pulimeng** [comment]
My bad. This is what you are looking for. The center for generating sphere grid after transformation should be [0,0,0], I mistakenly used the calculated center.
![test2](https://user-images.githubusercontent.com/22781918/76264970-4a701380-6231-11ea-935e-39111ac0ba1c.png)
But in order to remove redundant points, I think you need to have more conditions for filtering for your case.

**Comment by andrewleber** [comment]
So you inputed [0,0,0] in the aux file to get this?

Is there any overlap with the protein in yours as there was in my Dec 2, 2019 image? If not, then I suppose this is the answer

**Comment by pulimeng** [comment]
I meant this line in the above code `BS_original = sGrid(pocket_center, 15, 31)` should be `BS_original = sGrid(np.array([0,0,0]), 15, 31)`. I don't think there is overlap.
